--1 BUSCAR O NOME E ANO DOS FILMES
SELECT 
	Nome,
	Ano
FROM Filmes

--2 BUSCAR O NOME E ANO DOS FILMES, ORDENADOS POR ORDEM CRESCENTE PELO ANO
SELECT 
	Nome,
	Ano
FROM Filmes 
ORDER BY Ano

--3 BUSCAR PELO FILME 'DE VOLTA PARA O FUTURO', TRAZENDO O NOME ANO E DURAÇÃO
SELECT 
	Nome,
	Ano,
	Duracao
FROM Filmes
WHERE Nome = 'De Volta para o Futuro'

--4 BUSCAR OS FILMES LANÇADOS EM 1997
SELECT 
	Nome,
	Ano,
	Duracao
FROM Filmes
WHERE Ano = 1997

--5 BUSCAR OS FILMES LANÇADPS APÓS O ANO 2000
SELECT 
	Nome,
	Ano,
	Duracao
FROM Filmes
WHERE Ano > 2000

--6 BUSCAR OS FILMES COM A DURAÇÃO MAIOR QUE 100 E MENOR QUE 150, ORDENADO PELA DURAÇÃO EM ORDEM CRESCENTE
SELECT 
	Nome,
	Ano,
	Duracao
FROM Filmes
WHERE Duracao > 100 AND Duracao < 150
ORDER BY Duracao

--7 BUSCAR A QUANTIDADE DE FILMES LANÇADOS NO ANO, AGRUPANDO POR ANO, ORDENANDO PELA DURAÇÃO EM ORDEM DECRESCENTE
SELECT 
	Ano,
	COUNT(1) Quantidade
FROM Filmes
GROUP BY Ano
ORDER BY Quantidade DESC

--8 BUSCAR OS ATORES DO GÊNERO MASCULINO, RETORNANDO O PRIMEIRO NOME, ULTIMO NOME
SELECT 
	*
FROM Atores
WHERE Genero = 'M'

--9 BUSCAR OS ATORES DO GÊNERO FEMININO, RETORNANDO O PRIMEIRO NOME, ULTIMO NOME E ORDENANDO PELO PRIMEIRO NOME
SELECT
	*
FROM Atores
WHERE Genero = 'F'
ORDER BY PrimeiroNome

--10 BUSCAR O NOME DO FILME E O GÊNERO
SELECT
	f.Nome,
	g.Genero
FROM Filmes f
INNER JOIN FilmesGenero fg ON f.Id = fg.IdFilme
INNER JOIN Generos g ON fg.IdGenero = g.Id

--11 BUSCAR O NOME DO FILME E O GÊNERO do tipo "MISTÉRIO"
SELECT
	f.Nome,
	g.Genero
FROM Filmes f
INNER JOIN FilmesGenero fg ON f.Id = fg.IdFilme
INNER JOIN Generos g ON fg.IdGenero = g.Id
WHERE g.Genero = 'Mistério'

--12 BUSCAR O NOME DO FILME E OS ATORES, TRAZENDO O PRIMEIRO NOME, ULTIMO NOME E O SEU PAPEL
SELECT
	f.Nome,
	a.PrimeiroNome,
	a.UltimoNome,
	ef.Papel
FROM Filmes f
INNER JOIN ElencoFilme ef ON f.Id = ef.IdFilme
INNER JOIN Atores a ON ef.IdAtor = a.Id